# Ejercicios de la Biblioteca Numpy

##### II DIPLOMA DE EXPERTO EN APRENDIZAJE AUTOMÁTICO AVANZADO EN PYTHON
#### Alumno: Pablo Fazio Arrabal

---

In [1]:
import numpy as np

1. Escribe un programa que cree un array unidimensional con los enteros positivos múltiplos de 4 menores que 100.


In [4]:
enteros_array = np.arange(100)

lista_resultado = enteros_array[enteros_array % 4 == 0]

print(lista_resultado)

[ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92
 96]


2. Escribe un programa que cree un array bidimensional de 5 filas y 4 columnas con los enteros desde 0 hasta 19.


In [6]:
array_bidim = np.arange(20).reshape(5,4)

print(array_bidim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


3. Escribe un programa que invierte el orden de los elementos de un array unidimensional.

In [12]:
array_dim = np.array([3, 5, 6, 2, 1, -1, 8, 6, 78])

array_inv = array_dim[::-1]

print(array_inv)

[78  6  8 -1  1  2  6  5  3]


4. Escribe un programa que invierte el orden de las filas de un array bidimensional.


In [16]:
matriz = np.arange(3,15).reshape(4,3)

matriz_inv = matriz[::-1]

print(matriz_inv)

[[12 13 14]
 [ 9 10 11]
 [ 6  7  8]
 [ 3  4  5]]


5. Escribe un programa que calcule la media de los elementos de cada columna de un array bidimensional.

In [56]:
matriz_bi = np.arange(10,26).reshape(4,4)

medias = np.mean(matriz_bi, axis = 0)

print(medias)

[16. 17. 18. 19.]


6. Escribe un programa que redimensione un array unidimensional a un array bidimensional con 4 filas y 3 columnas.

In [20]:
array_uni = np.arange(12)

array_reshaped = array_uni.reshape(4,3)

print(array_reshaped)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


7. Escribe un programa que, dado un array unidimensional, compruebe si se puede redimensionar a un array bidimensional con el mismo número de filas y columnas (matriz cuadrada). En caso afirmativo, debe imprimir la matriz cuadrada. En caso negativo, debe imprimir un mensaje informativo.

In [30]:
def comprobar_redimension(array_uni):
  dimension = np.sqrt(np.size(array_uni))
  if dimension % 1 == 0:
    print(array_uni.reshape(int(dimension), int(dimension)))
  else:
    print("Error: dimesión no válida")

In [34]:
array_uni = np.array([1,2,3,4,5,6,7,8,9])
comprobar_redimension(array_uni)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


8. Escribe un programa que, dado un array bidimensional, halle el máximo de cada fila.


In [57]:
maximo_filas = np.max(matriz_bi, axis = 1)

print(maximo_filas)

[13 17 21 25]


9. Escribe un programa que, dado un array unidimensional, halle el número de veces que aparece cada uno de sus elementos únicos.

In [24]:
vector_aleat = np.random.randint(1, 100, 1_000_000)

unique_numbers, count = np.unique(vector_aleat, return_counts = True)

print(count)

[10306 10018 10262  9986 10210 10135 10214 10100 10170  9963 10142 10160
 10057 10037 10123 10009 10102 10151 10000 10154 10099 10131  9897 10017
  9874 10183 10048 10102  9952 10113 10003 10194  9979  9982  9908 10012
 10285  9798 10196 10139 10150 10114  9961 10187 10158  9968 10199 10085
  9933 10098  9968 10167 10111 10175 10185 10002 10193 10098 10095 10007
 10032 10177 10252 10286 10090 10098 10221 10053 10137 10046  9968 10226
  9971 10156  9997 10047 10167 10158 10265 10097 10113 10279 10121 10098
 10188 10126  9984 10151 10032 10189 10232 10008 10193 10166  9922 10215
 10076 10287 10111]


10. Normaliza un array bidimensional de 4 filas y 3 columnas restando la media y dividiendo por la desviación típica en cada columna.

In [66]:
dist_normal = np.random.normal(5, 3, size=(4,3))

media_cols = np.mean(dist_normal, axis=0)
std_cols = np.std(dist_normal, axis=0)

array_normalizado_cols = (dist_normal - media_cols) / std_cols

print(array_normalizado_cols)

[[ 0.01349915 -1.71965661 -0.67365293]
 [-1.37446857  0.41245994  0.27133005]
 [-0.08910449  0.74919223 -1.10107508]
 [ 1.4500739   0.55800444  1.50339796]]


11. Normaliza un array bidimensional de 4 filas y 3 columnas restando la media y dividiendo por la desviación típica en cada fila.

In [65]:
media_filas = np.mean(dist_normal, axis=1, keepdims=True)
std_filas = np.std(dist_normal, axis=1, keepdims=True)

array_normalizado_filas = (dist_normal - media_filas) / std_filas

print(array_normalizado_filas)

[[ 0.69355752  0.72057005 -1.41412757]
 [ 1.33692758 -0.26912873 -1.06779885]
 [ 1.36194412 -0.35107638 -1.01086774]
 [ 0.80836391  0.60076125 -1.40912516]]


12. Escribe un programa que, dado un array bidimensional, halle los índices (filas y columnas) de los elementos mínimo y máximo del array.


In [53]:
matriz_random = np.random.normal(size = (4, 5))

idx_min, idx_max = np.argmin(matriz_random), np.argmax(matriz_random)

fila_min, col_min = np.unravel_index(idx_min, np.shape(matriz_random))

fila_max, col_max = np.unravel_index(idx_max, np.shape(matriz_random))

print(f"El índice del elemento mínimo es: [{fila_min}][{col_min}]")

print(f"El índice del elemento máximo es: [{fila_max}][{col_max}]")

El índice del elemento mínimo es: [2][1]
El índice del elemento máximo es: [1][1]


13. Escribe un programa que ordene las filas de un array bidimensional según los valores de la primera columna.

In [60]:
matriz_random = np.random.normal(size = (4, 5))

matriz_ordenada = matriz_random[np.argsort(matriz_random[:, 0])]

print(matriz_ordenada)

[[-1.22487861  2.45700927  0.87531189 -0.40767124  0.41582419]
 [-0.22538244 -1.31466058 -0.41133748 -0.15198115 -0.16481352]
 [ 1.19431118  1.14992786  0.05472331  1.23113733 -0.69864324]
 [ 2.01183162  0.03682463 -0.70686519 -0.76396426  1.705655  ]]


14. Escribe un programa que genere una matriz bidimensional con 7 filas y 5 columnas aleatoriamente de acuerdo a la distribución normal, y a continuación ponga a cero todos los elementos negativos.


In [40]:
matriz_normal = np.random.normal(size = (7, 5))

matriz_normal[matriz_normal < 0] = 0

print(matriz_normal)

[[0.         0.         0.56244146 0.         0.45896381]
 [0.42000728 0.         0.         0.6985032  0.        ]
 [0.01700623 0.         1.55622077 0.98418527 1.30552733]
 [0.29756741 0.02274652 0.         0.58569724 0.        ]
 [0.21581292 0.         0.         0.         0.        ]
 [1.23266353 0.         0.         1.21980864 0.35226992]
 [0.         0.         0.19784448 0.         0.        ]]


15. Escribe un programa que, dado un array unidimensional y un número entero positivo k, halle los índices de los k mayores valores del array.

In [69]:
k = 3
array_unid = np.array([3,4,5,6,2,3,-1,8,90])

indices_top_k = np.argsort(array_unid)[-k:]

print(indices_top_k)

[3 7 8]


16. Escribe un programa que genere una matriz bidimensional con 6 filas y 7 columnas aleatoriamente de acuerdo a la distribución uniforme, y a continuación ponga a cero las dos primeras columnas y a uno las tres últimas columnas.

In [38]:
matriz_ejemplo = np.random.uniform(size = (6, 7))

matriz_ejemplo[:, [0,1]] = 0

matriz_ejemplo[:, [-1,-2,-3]] = 1

print(matriz_ejemplo)

[[0.         0.         0.30682528 0.49203785 1.         1.
  1.        ]
 [0.         0.         0.75595379 0.17103746 1.         1.
  1.        ]
 [0.         0.         0.58689529 0.31862925 1.         1.
  1.        ]
 [0.         0.         0.40416557 0.40481953 1.         1.
  1.        ]
 [0.         0.         0.3455064  0.47900066 1.         1.
  1.        ]
 [0.         0.         0.37820175 0.76783894 1.         1.
  1.        ]]
